<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/* 
 *    This file is part of simple_http.

 *    simple_http is free software: you can redistribute it and/or modify
 *    it under the terms of the Apache License, Version 2.0 (See License at the
 *    top of the directory).

 *    simple_http is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 *    You should have received a copy of the Apache License, Version 2.0
 *    along with simple_http.  If not, see <http://www.apache.org/licenses/LICENSE-2.0.html>.
 */

/**
 * Description of SimpleHTTP. Include this file to include the entire library.
 *
 * @author olendorf
 *
 */
require_once 'HTTPCompression.inc';
require_once 'HTTPRequestHeaders.inc';
require_once 'HTTPResponseHeaders.inc';
require_once 'HTTPStatusCodes.inc';
require_once 'SimpleHTTPRequest.php';
require_once 'SimpleHTTPResponse.php';

?>
