<?php
/* 
 *    This file is part of curation_tool.

 *    curation_tool is free software: you can redistribute it and/or modify
 *    it under the terms of the Apache License, Version 2.0 (See License at the
 *    top of the directory).

 *    curation_tool is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 *    You should have received a copy of the Apache License, Version 2.0
 *    along with data_curation.  If not, see <http://www.apache.org/licenses/LICENSE-2.0.html>.
 */
/**
 * Primary module for the curation tool package which serves as a front end for
 * the data curation class libarary.
 * 
 * @author Robert Olendorf
 * @license Apache Licesnse 2.0 
 */

function curation_tool_help($path, $arg) {
  if($path == 'admin/help/#curation_tool') {
    return t('A drupal frontend for the data curation library.');
  }
}

/**
 * Implements hook_menu
 * @todo add access control
 * 
 * @return array 
 */
function curation_tool_menu() {
  $items = array();
  
  $items['admin/config/curation_tool'] = array(
      'title' => 'Curation Tool',
      'description' => 'Configuration for the Curation Tool Module',
      'page callback' => 'drupal_get_form',
      'file path' => 'sites/all/modules/curation_tool/forms',
      'file' => 'admin_forms.php',
      'page arguments' => array('curation_tool_admin_form'),
      'access arguments' => array('administer curation tool'),
      'type' => MENU_NORMAL_ITEM,
  );
  
  $items['user/project'] = array(
      'title' => 'Project',
      'menu_name' => 'navigation',
      'access callback' => TRUE,
      'expanded' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      );
  
  $items['user/project/add'] = array(
      'title' => 'New Project',
      'description' => 'Create a new data project.',
      'file path' => 'sites/all/modules/curation_tool/forms',
      'file' => 'new_project_wizard.php',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('form_new_project_wizard'),
      'access arguments' => array('create own project'),
      'parent' => 'user/project',
      'type' => MENU_NORMAL_ITEM,
      'menu_name' => 'navigation',
  );
  
  $items['users/project/add/meta'] = array(
      'title' => 'Descriptive Metadata.',
      'description' => 'Create descriptive metadata for the project using '.
                        'the Qualified Dublin Core vocabulary.',
      'file' => 'project_form.php',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('project_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function curation_tool_permission() {
  return array(
      'administer curation tool' => array(
          'title' => t('Administer curation tool'),
          'description' => t('Change settings for the curation too module'),
          'restrict access' => TRUE,
      ),
      'create any project' => array(
          'title' => t('Create any project'),
          'description' => t('Create a project for any account'),
          'restrict access' => TRUE,
      ),
      'create own project' => array(
          'title' => t('Create own project'),
      ),
      'delete any project' => array(
          'title' => t('Delete any project'),
          'description' => t('Delete a project from any account'),
          'restrict access' => TRUE,
      ),
      'delete own project' => array(
          'title' => t('Delete own projects'),
          'description' => t('Delete a project from a user&apos;s own account'),
      ),
      'edit any project' => array(
          'title' => t('Edit any project'),
          'description' => t('Edit projects from any account'),
          'restrict access' => TRUE,
      ),
      'edit own project' => array(
          'title' => t('Edit own projects'),
          'description' => t('Edit a project from a user&apos;s own account'),
      ),
  );
}