<?php

/**
 * Primary module for the curatoin tool package which serves as a front end for
 * the data curation class libarary.
 * 
 * @author Robert Olendorf
 * @license Apache Licesnse 2.0 
 */

function curation_tool_help($path, $arg) {
  if($path == 'admin/help/#curation_tool') {
    return t('A drupal frontend for the data curation library.');
  }
}

/**
 * Implements hook_menu
 * @todo add access control
 * 
 * @return array 
 */
function curation_tool_menu() {
  $items = array();
  
  $items['admin/config/curation_tool'] = array(
      'title' => 'Curation Tool',
      'description' => 'Configuration for the Curation Tool Module',
      'page callback' => 'drupal_get_form',
      'file path' => 'sites/all/modules/curation_tool/forms',
      'file' => 'admin_forms.php',
      'page arguments' => array('curation_tool_admin_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  
  $items['user/project'] = array(
      'title' => 'Project',
      'menu_name' => 'navigation',
      'access callback' => TRUE,
      'expanded' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      );
  
  $items['user/project/add'] = array(
      'title' => 'Create Project',
      'description' => 'Create a new data project.',
      'file path' => 'sites/all/modules/curation_tool/forms',
      'file' => 'project_forms.php',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('curation_tool_new_project_form'),
      'access callback' => TRUE,
      'parent' => 'user/project',
      'type' => MENU_NORMAL_ITEM,
      'menu_name' => 'navigation',
  );
  
  return $items;
}

function curation_tool_permission() {
  return array(
      'administer curation tool' => array(
          'title' => t('Administer curation tool'),
          'description' => t('Change settings for the curation too module'),
          'restrict access' => TRUE,
      ),
      'create any project' => array(
          'title' => t('Create any project'),
          'description' => t('Create a project for any account'),
          'restrict access' => TRUE,
      ),
      'create own project' => array(
          'title' => t('Create own project'),
      ),
      'delete any project' => array(
          'title' => t('Delete any project'),
          'description' => t('Delete a project from any account'),
          'restrict access' => TRUE,
      ),
      'delete own project' => array(
          'title' => t('Delete own projects'),
          'description' => t('Delete a project from a user&apos;s own account'),
      ),
      'edit any project' => array(
          'title' => t('Edit any project'),
          'description' => t('Edit projects from any account'),
          'restrict access' => TRUE,
      ),
      'edit own project' => array(
          'title' => t('Edit own projects'),
          'description' => t('Edit a project from a user&apos;s own account'),
      ),
  );
}

?>